/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_workspace_plugin_workspace_contextSnapshot_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_contextSnapshot_result$schema = z.object({
  'version': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'estimatedTokens': z.number().readonly(),
  'capacityTokens': z.number().readonly(),
  'admittedTokens': z.number().readonly(),
  'availableBudgetTokens': z.number().readonly(),
  'remainingTokens': z.number().readonly(),
  'status': z.union([z.literal("ready"), z.literal("omitted")]).readonly(),
  'omissionReason': z.string().readonly(),
})
const dsh_workspace_plugin_workspace_focus_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_focus_result$schema = z.object({
  'focused': z.boolean().readonly(),
})
const dsh_workspace_plugin_workspace_replaceContext_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_replaceContext_parameter_0$schema = z.object({
  'version': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'estimatedTokens': z.number().readonly(),
  'capacityTokens': z.number().readonly(),
  'admittedTokens': z.number().readonly(),
  'availableBudgetTokens': z.number().readonly(),
  'remainingTokens': z.number().readonly(),
  'status': z.union([z.literal("ready"), z.literal("omitted")]).readonly(),
  'omissionReason': z.string().readonly(),
})
const dsh_workspace_plugin_workspace_replaceContext_result$schema = z.object({
  'version': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'estimatedTokens': z.number().readonly(),
  'capacityTokens': z.number().readonly(),
  'admittedTokens': z.number().readonly(),
  'availableBudgetTokens': z.number().readonly(),
  'remainingTokens': z.number().readonly(),
  'status': z.union([z.literal("ready"), z.literal("omitted")]).readonly(),
  'omissionReason': z.string().readonly(),
})
const dsh_workspace_plugin_workspace_summary_parameter_0$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_summary_result$schema = z.object({
  'ready': z.boolean().readonly(),
  'agent': z.intersection(z.string(), z.unknown()).readonly(),
})

export const TYPERT = {
  package: 'dsh-workspace-plugin',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-workspace-plugin#workspace/contextSnapshot',
      service: 'workspace',
      namespace: 'workspace',
      method: 'contextSnapshot',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_contextSnapshot_context$schema,
        },
      },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#PinnedContextRemoteSnapshot',
        schema: dsh_workspace_plugin_workspace_contextSnapshot_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":108,"column":3},
    },
    {
      id: 'dsh-workspace-plugin#workspace/focus',
      service: 'workspace',
      namespace: 'workspace',
      method: 'focus',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_focus_context$schema,
        },
      },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin#workspace/focus:result',
        schema: dsh_workspace_plugin_workspace_focus_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":103,"column":3},
    },
    {
      id: 'dsh-workspace-plugin#workspace/replaceContext',
      service: 'workspace',
      namespace: 'workspace',
      method: 'replaceContext',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_replaceContext_context$schema,
        },
      },
      parameters: [
        {
          name: 'snapshot',
          wire: 'snapshot',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#PinnedContextRemoteSnapshot',
            schema: dsh_workspace_plugin_workspace_replaceContext_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#PinnedContextRemoteSnapshot',
        schema: dsh_workspace_plugin_workspace_replaceContext_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":113,"column":3},
    },
    {
      id: 'dsh-workspace-plugin#workspace/summary',
      service: 'workspace',
      namespace: 'workspace',
      method: 'summary',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'agent',
          wire: 'agent',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#AgentId',
            schema: dsh_workspace_plugin_workspace_summary_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin#workspace/summary:result',
        schema: dsh_workspace_plugin_workspace_summary_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":98,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
