/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { WorkspaceDeliverable } from 'dsh-workspace-plugin/client'
import type { AgentId, MemoryDraft, MemoryGovernanceAction, MemoryListOptions, MemoryReadState, MemoryRecord, MemoryScopeRequest, MemorySearchOptions, PinnedContextRemoteSnapshot, WorkspaceArtifactPreview } from 'dsh-workspace-plugin/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$776f726b7370616365 {
    summary: (agent: AgentId) => Promise<RemoteResult<{ readonly ready: boolean; readonly agent: AgentId; }>>
  }
  interface TypertRemoteMap {
    'workspace/summary': (agent: AgentId) => Promise<RemoteResult<{ readonly ready: boolean; readonly agent: AgentId; }>>
  }
  interface TypertRemoteNamespaceMap {
    'workspace': TypertRemoteNamespace$776f726b7370616365
  }
  interface TypertRemoteScopeMap {
    'agent:workspace/artifactMetadata': () => Promise<RemoteResult<readonly WorkspaceDeliverable[]>>
    'agent:workspace/contextSnapshot': () => Promise<RemoteResult<PinnedContextRemoteSnapshot>>
    'agent:workspace/focus': () => Promise<RemoteResult<{ readonly focused: boolean; }>>
    'agent:workspace/memoryArchive': (request: MemoryScopeRequest, id: string, expectedRevision: number, expectedHash: string) => Promise<RemoteResult<MemoryRecord>>
    'agent:workspace/memoryClose': (request: MemoryScopeRequest) => Promise<RemoteResult<void>>
    'agent:workspace/memoryExport': (request: MemoryScopeRequest) => Promise<RemoteResult<string>>
    'agent:workspace/memoryForget': (request: MemoryScopeRequest, id: string, expectedRevision: number, expectedHash: string) => Promise<RemoteResult<MemoryRecord>>
    'agent:workspace/memoryGovern': (request: MemoryScopeRequest, id: string, action: MemoryGovernanceAction, expectedRevision: number, expectedHash: string) => Promise<RemoteResult<MemoryRecord>>
    'agent:workspace/memoryImport': (request: MemoryScopeRequest, serialized: string) => Promise<RemoteResult<readonly MemoryRecord[]>>
    'agent:workspace/memoryList': (request: MemoryScopeRequest, options?: MemoryListOptions) => Promise<RemoteResult<readonly MemoryRecord[]>>
    'agent:workspace/memoryMarkUsed': (request: MemoryScopeRequest, id: string) => Promise<RemoteResult<MemoryRecord>>
    'agent:workspace/memoryOpen': (request: MemoryScopeRequest) => Promise<RemoteResult<MemoryReadState>>
    'agent:workspace/memorySearch': (request: MemoryScopeRequest, query: string, options?: MemorySearchOptions) => Promise<RemoteResult<readonly MemoryRecord[]>>
    'agent:workspace/memoryUpsert': (request: MemoryScopeRequest, draft: MemoryDraft) => Promise<RemoteResult<MemoryRecord>>
    'agent:workspace/previewArtifact': (id: string) => Promise<RemoteResult<WorkspaceArtifactPreview>>
    'agent:workspace/replaceContext': (snapshot: PinnedContextRemoteSnapshot) => Promise<RemoteResult<PinnedContextRemoteSnapshot>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
