/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { AgentId, PinnedContextRemoteSnapshot } from 'dsh-workspace-plugin/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$776f726b7370616365 {
    summary: (agent: AgentId) => Promise<RemoteResult<{ readonly ready: boolean; readonly agent: AgentId; }>>
  }
  interface TypertRemoteMap {
    'workspace/summary': (agent: AgentId) => Promise<RemoteResult<{ readonly ready: boolean; readonly agent: AgentId; }>>
  }
  interface TypertRemoteNamespaceMap {
    'workspace': TypertRemoteNamespace$776f726b7370616365
  }
  interface TypertRemoteScopeMap {
    'agent:workspace/contextSnapshot': () => Promise<RemoteResult<PinnedContextRemoteSnapshot>>
    'agent:workspace/focus': () => Promise<RemoteResult<{ readonly focused: boolean; }>>
    'agent:workspace/replaceContext': (snapshot: PinnedContextRemoteSnapshot) => Promise<RemoteResult<PinnedContextRemoteSnapshot>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
