/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
export const TYPERT = {
  package: 'dsh-workspace-plugin',
  face: 'client',
  schemas: [
  ],
  invocations: [
  ],
  model: {
    "services": [],
    "events": [
      {
        "tags": [],
        "name": "workspace/open",
        "signature": "'workspace/open'(): void"
      }
    ],
    "objects": [
      {
        "tags": [
          {
            "name": "typert",
            "comment": "object",
            "text": "@typert object"
          }
        ],
        "jsDoc": "/** @typert object */",
        "name": "WorkspaceClientSurface",
        "exportName": "WorkspaceClientSurface",
        "members": [
          {
            "kind": "property",
            "name": "ready",
            "signature": "readonly ready: boolean"
          }
        ],
        "types": []
      }
    ]
  },
}
