/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const WorkspaceJsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => WorkspaceJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => WorkspaceJsonValueRemoteCodec$schema)).readonly()])
const dsh_workspace_plugin_workspace_artifactMetadata_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_artifactMetadata_result$schema = z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'mediaType': z.string().readonly(),
  'sizeBytes': z.number().readonly(),
  'version': z.union([z.undefined(), z.string()]).readonly().optional(),
  'source': z.object({
  'sessionId': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'kind': z.union([z.literal("artifact"), z.literal("file")]).readonly(),
}).readonly(),
  'preview': z.union([z.literal("available"), z.literal("unsupported"), z.literal("oversized"), z.literal("stale")]).readonly(),
  'resourceId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'downloadName': z.string().readonly(),
  'altText': z.union([z.undefined(), z.string()]).readonly().optional(),
}))
const dsh_workspace_plugin_workspace_contextSnapshot_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_contextSnapshot_result$schema = z.object({
  'version': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'estimatedTokens': z.number().readonly(),
  'capacityTokens': z.number().readonly(),
  'admittedTokens': z.number().readonly(),
  'availableBudgetTokens': z.number().readonly(),
  'remainingTokens': z.number().readonly(),
  'status': z.union([z.literal("ready"), z.literal("omitted")]).readonly(),
  'omissionReason': z.string().readonly(),
})
const dsh_workspace_plugin_workspace_focus_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_focus_result$schema = z.object({
  'focused': z.boolean().readonly(),
})
const dsh_workspace_plugin_workspace_memoryArchive_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_memoryArchive_parameter_0$schema = z.object({
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'userId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sharedProject': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_workspace_plugin_workspace_memoryArchive_parameter_1$schema = z.string()
const dsh_workspace_plugin_workspace_memoryArchive_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'id': z.string().readonly(),
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'scopeKey': z.string().readonly(),
  'type': z.union([z.literal("decision"), z.literal("preference"), z.literal("convention"), z.literal("fact")]).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'provenance': z.object({
  'kind': z.union([z.literal("user"), z.literal("agent"), z.literal("tool"), z.literal("import")]).readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'eventSeq': z.union([z.undefined(), z.number()]).readonly().optional(),
  'note': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
  'lastUsedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'useCount': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'status': z.union([z.literal("active"), z.literal("archived"), z.literal("forgotten")]).readonly(),
})
const dsh_workspace_plugin_workspace_memoryClose_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_memoryClose_parameter_0$schema = z.object({
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'userId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sharedProject': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_workspace_plugin_workspace_memoryClose_result$schema = z.void()
const dsh_workspace_plugin_workspace_memoryForget_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_memoryForget_parameter_0$schema = z.object({
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'userId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sharedProject': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_workspace_plugin_workspace_memoryForget_parameter_1$schema = z.string()
const dsh_workspace_plugin_workspace_memoryForget_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'id': z.string().readonly(),
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'scopeKey': z.string().readonly(),
  'type': z.union([z.literal("decision"), z.literal("preference"), z.literal("convention"), z.literal("fact")]).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'provenance': z.object({
  'kind': z.union([z.literal("user"), z.literal("agent"), z.literal("tool"), z.literal("import")]).readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'eventSeq': z.union([z.undefined(), z.number()]).readonly().optional(),
  'note': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
  'lastUsedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'useCount': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'status': z.union([z.literal("active"), z.literal("archived"), z.literal("forgotten")]).readonly(),
})
const dsh_workspace_plugin_workspace_memoryList_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_memoryList_parameter_0$schema = z.object({
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'userId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sharedProject': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_workspace_plugin_workspace_memoryList_parameter_1$schema = z.union([z.undefined(), z.object({
  'type': z.union([z.undefined(), z.literal("decision"), z.literal("preference"), z.literal("convention"), z.literal("fact")]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("active"), z.literal("archived"), z.literal("forgotten")]).readonly().optional(),
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
})])
const dsh_workspace_plugin_workspace_memoryList_result$schema = z.array(z.object({
  'schemaVersion': z.literal(1).readonly(),
  'id': z.string().readonly(),
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'scopeKey': z.string().readonly(),
  'type': z.union([z.literal("decision"), z.literal("preference"), z.literal("convention"), z.literal("fact")]).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'provenance': z.object({
  'kind': z.union([z.literal("user"), z.literal("agent"), z.literal("tool"), z.literal("import")]).readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'eventSeq': z.union([z.undefined(), z.number()]).readonly().optional(),
  'note': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
  'lastUsedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'useCount': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'status': z.union([z.literal("active"), z.literal("archived"), z.literal("forgotten")]).readonly(),
}))
const dsh_workspace_plugin_workspace_memoryMarkUsed_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_memoryMarkUsed_parameter_0$schema = z.object({
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'userId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sharedProject': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_workspace_plugin_workspace_memoryMarkUsed_parameter_1$schema = z.string()
const dsh_workspace_plugin_workspace_memoryMarkUsed_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'id': z.string().readonly(),
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'scopeKey': z.string().readonly(),
  'type': z.union([z.literal("decision"), z.literal("preference"), z.literal("convention"), z.literal("fact")]).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'provenance': z.object({
  'kind': z.union([z.literal("user"), z.literal("agent"), z.literal("tool"), z.literal("import")]).readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'eventSeq': z.union([z.undefined(), z.number()]).readonly().optional(),
  'note': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
  'lastUsedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'useCount': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'status': z.union([z.literal("active"), z.literal("archived"), z.literal("forgotten")]).readonly(),
})
const dsh_workspace_plugin_workspace_memoryOpen_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_memoryOpen_parameter_0$schema = z.object({
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'userId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sharedProject': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_workspace_plugin_workspace_memoryOpen_result$schema = z.object({
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'scopeKey': z.string().readonly(),
  'records': z.array(z.object({
  'schemaVersion': z.literal(1).readonly(),
  'id': z.string().readonly(),
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'scopeKey': z.string().readonly(),
  'type': z.union([z.literal("decision"), z.literal("preference"), z.literal("convention"), z.literal("fact")]).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'provenance': z.object({
  'kind': z.union([z.literal("user"), z.literal("agent"), z.literal("tool"), z.literal("import")]).readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'eventSeq': z.union([z.undefined(), z.number()]).readonly().optional(),
  'note': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
  'lastUsedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'useCount': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'status': z.union([z.literal("active"), z.literal("archived"), z.literal("forgotten")]).readonly(),
})).readonly(),
  'warnings': z.array(z.object({
  'code': z.union([z.literal("CORRUPT_RECORD"), z.literal("BAD_HASH"), z.literal("UNSUPPORTED_SCHEMA"), z.literal("TRUNCATED_LINE")]).readonly(),
  'line': z.number().readonly(),
  'message': z.string().readonly(),
})).readonly(),
  'readOnly': z.boolean().readonly(),
})
const dsh_workspace_plugin_workspace_memorySearch_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_memorySearch_parameter_0$schema = z.object({
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'userId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sharedProject': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_workspace_plugin_workspace_memorySearch_parameter_1$schema = z.string()
const dsh_workspace_plugin_workspace_memorySearch_parameter_2$schema = z.union([z.undefined(), z.object({
  'limit': z.union([z.undefined(), z.number()]).readonly().optional(),
  'type': z.union([z.undefined(), z.literal("decision"), z.literal("preference"), z.literal("convention"), z.literal("fact")]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("active"), z.literal("archived"), z.literal("forgotten")]).readonly().optional(),
})])
const dsh_workspace_plugin_workspace_memorySearch_result$schema = z.array(z.object({
  'schemaVersion': z.literal(1).readonly(),
  'id': z.string().readonly(),
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'scopeKey': z.string().readonly(),
  'type': z.union([z.literal("decision"), z.literal("preference"), z.literal("convention"), z.literal("fact")]).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'provenance': z.object({
  'kind': z.union([z.literal("user"), z.literal("agent"), z.literal("tool"), z.literal("import")]).readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'eventSeq': z.union([z.undefined(), z.number()]).readonly().optional(),
  'note': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
  'lastUsedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'useCount': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'status': z.union([z.literal("active"), z.literal("archived"), z.literal("forgotten")]).readonly(),
}))
const dsh_workspace_plugin_workspace_memoryUpsert_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_memoryUpsert_parameter_0$schema = z.object({
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'userId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'sharedProject': z.union([z.undefined(), z.literal(false), z.literal(true)]).readonly().optional(),
})
const dsh_workspace_plugin_workspace_memoryUpsert_parameter_1$schema = z.intersection(z.object({
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'scopeKey': z.string().readonly(),
  'type': z.union([z.literal("decision"), z.literal("preference"), z.literal("convention"), z.literal("fact")]).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'provenance': z.object({
  'kind': z.union([z.literal("user"), z.literal("agent"), z.literal("tool"), z.literal("import")]).readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'eventSeq': z.union([z.undefined(), z.number()]).readonly().optional(),
  'note': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'id': z.union([z.undefined(), z.string()]).readonly().optional(),
  'createdAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'updatedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'lastUsedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'useCount': z.union([z.undefined(), z.number()]).readonly().optional(),
  'status': z.union([z.undefined(), z.literal("active"), z.literal("archived"), z.literal("forgotten")]).readonly().optional(),
}))
const dsh_workspace_plugin_workspace_memoryUpsert_result$schema = z.object({
  'schemaVersion': z.literal(1).readonly(),
  'id': z.string().readonly(),
  'scope': z.union([z.literal("session"), z.literal("project"), z.literal("user"), z.literal("shared-project")]).readonly(),
  'scopeKey': z.string().readonly(),
  'type': z.union([z.literal("decision"), z.literal("preference"), z.literal("convention"), z.literal("fact")]).readonly(),
  'title': z.string().readonly(),
  'content': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'provenance': z.object({
  'kind': z.union([z.literal("user"), z.literal("agent"), z.literal("tool"), z.literal("import")]).readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'eventSeq': z.union([z.undefined(), z.number()]).readonly().optional(),
  'note': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
  'lastUsedAt': z.union([z.undefined(), z.number()]).readonly().optional(),
  'useCount': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'status': z.union([z.literal("active"), z.literal("archived"), z.literal("forgotten")]).readonly(),
})
const dsh_workspace_plugin_workspace_previewArtifact_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_previewArtifact_parameter_0$schema = z.string()
const dsh_workspace_plugin_workspace_previewArtifact_result$schema = z.union([z.object({
  'type': z.literal("text").readonly(),
  'renderer': z.literal("ui-primitives").readonly(),
  'language': z.union([z.undefined(), z.string()]).readonly().optional(),
  'content': z.string().readonly(),
  'truncated': z.boolean().readonly(),
}), z.object({
  'type': z.literal("markdown").readonly(),
  'renderer': z.literal("ui-primitives").readonly(),
  'content': z.string().readonly(),
  'truncated': z.boolean().readonly(),
  'policy': z.object({
  'allowRawHtml': z.literal(false).readonly(),
  'allowRemoteImages': z.literal(false).readonly(),
  'allowedLinkSchemes': z.tuple([z.literal("http"), z.literal("https"), z.literal("mailto")]).readonly(),
}).readonly(),
}), z.object({
  'type': z.literal("json").readonly(),
  'renderer': z.literal("ui-primitives").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => WorkspaceJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => WorkspaceJsonValueRemoteCodec$schema)).readonly()]).readonly(),
}), z.object({
  'type': z.literal("csv").readonly(),
  'renderer': z.literal("ui-primitives").readonly(),
  'columns': z.array(z.string()).readonly(),
  'rows': z.array(z.array(z.string())).readonly(),
  'truncated': z.boolean().readonly(),
}), z.object({
  'type': z.literal("binary").readonly(),
  'mediaType': z.string().readonly(),
  'resourceId': z.string().readonly(),
  'version': z.string().readonly(),
  'expiresAt': z.number().readonly(),
}), z.object({
  'type': z.literal("unsupported").readonly(),
  'reason': z.string().readonly(),
  'mediaType': z.union([z.undefined(), z.string()]).readonly().optional(),
  'size': z.union([z.undefined(), z.number()]).readonly().optional(),
}), z.object({
  'type': z.literal("error").readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
})])
const dsh_workspace_plugin_workspace_replaceContext_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_replaceContext_parameter_0$schema = z.object({
  'version': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'estimatedTokens': z.number().readonly(),
  'capacityTokens': z.number().readonly(),
  'admittedTokens': z.number().readonly(),
  'availableBudgetTokens': z.number().readonly(),
  'remainingTokens': z.number().readonly(),
  'status': z.union([z.literal("ready"), z.literal("omitted")]).readonly(),
  'omissionReason': z.string().readonly(),
})
const dsh_workspace_plugin_workspace_replaceContext_result$schema = z.object({
  'version': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'estimatedTokens': z.number().readonly(),
  'capacityTokens': z.number().readonly(),
  'admittedTokens': z.number().readonly(),
  'availableBudgetTokens': z.number().readonly(),
  'remainingTokens': z.number().readonly(),
  'status': z.union([z.literal("ready"), z.literal("omitted")]).readonly(),
  'omissionReason': z.string().readonly(),
})
const dsh_workspace_plugin_workspace_summary_parameter_0$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_summary_result$schema = z.object({
  'ready': z.boolean().readonly(),
  'agent': z.intersection(z.string(), z.unknown()).readonly(),
})

export const TYPERT = {
  package: 'dsh-workspace-plugin',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-workspace-plugin#workspace/artifactMetadata',
      service: 'workspace',
      namespace: 'workspace',
      method: 'artifactMetadata',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_artifactMetadata_context$schema,
        },
      },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin#workspace/artifactMetadata:result',
        schema: dsh_workspace_plugin_workspace_artifactMetadata_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":171,"column":9},
    },
    {
      id: 'dsh-workspace-plugin#workspace/contextSnapshot',
      service: 'workspace',
      namespace: 'workspace',
      method: 'contextSnapshot',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_contextSnapshot_context$schema,
        },
      },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#PinnedContextRemoteSnapshot',
        schema: dsh_workspace_plugin_workspace_contextSnapshot_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":160,"column":3},
    },
    {
      id: 'dsh-workspace-plugin#workspace/focus',
      service: 'workspace',
      namespace: 'workspace',
      method: 'focus',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_focus_context$schema,
        },
      },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin#workspace/focus:result',
        schema: dsh_workspace_plugin_workspace_focus_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":155,"column":3},
    },
    {
      id: 'dsh-workspace-plugin#workspace/memoryArchive',
      service: 'workspace',
      namespace: 'workspace',
      method: 'memoryArchive',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_memoryArchive_context$schema,
        },
      },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#MemoryScopeRequest',
            schema: dsh_workspace_plugin_workspace_memoryArchive_parameter_0$schema,
          },
        },
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin#workspace/memoryArchive:id',
            schema: dsh_workspace_plugin_workspace_memoryArchive_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#MemoryRecord',
        schema: dsh_workspace_plugin_workspace_memoryArchive_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":197,"column":9},
    },
    {
      id: 'dsh-workspace-plugin#workspace/memoryClose',
      service: 'workspace',
      namespace: 'workspace',
      method: 'memoryClose',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_memoryClose_context$schema,
        },
      },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#MemoryScopeRequest',
            schema: dsh_workspace_plugin_workspace_memoryClose_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin#workspace/memoryClose:result',
        schema: dsh_workspace_plugin_workspace_memoryClose_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":217,"column":9},
    },
    {
      id: 'dsh-workspace-plugin#workspace/memoryForget',
      service: 'workspace',
      namespace: 'workspace',
      method: 'memoryForget',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_memoryForget_context$schema,
        },
      },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#MemoryScopeRequest',
            schema: dsh_workspace_plugin_workspace_memoryForget_parameter_0$schema,
          },
        },
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin#workspace/memoryForget:id',
            schema: dsh_workspace_plugin_workspace_memoryForget_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#MemoryRecord',
        schema: dsh_workspace_plugin_workspace_memoryForget_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":202,"column":9},
    },
    {
      id: 'dsh-workspace-plugin#workspace/memoryList',
      service: 'workspace',
      namespace: 'workspace',
      method: 'memoryList',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_memoryList_context$schema,
        },
      },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#MemoryScopeRequest',
            schema: dsh_workspace_plugin_workspace_memoryList_parameter_0$schema,
          },
        },
        {
          name: 'options',
          wire: 'options',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#MemoryListOptions',
            schema: dsh_workspace_plugin_workspace_memoryList_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin#workspace/memoryList:result',
        schema: dsh_workspace_plugin_workspace_memoryList_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":187,"column":9},
    },
    {
      id: 'dsh-workspace-plugin#workspace/memoryMarkUsed',
      service: 'workspace',
      namespace: 'workspace',
      method: 'memoryMarkUsed',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_memoryMarkUsed_context$schema,
        },
      },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#MemoryScopeRequest',
            schema: dsh_workspace_plugin_workspace_memoryMarkUsed_parameter_0$schema,
          },
        },
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin#workspace/memoryMarkUsed:id',
            schema: dsh_workspace_plugin_workspace_memoryMarkUsed_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#MemoryRecord',
        schema: dsh_workspace_plugin_workspace_memoryMarkUsed_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":212,"column":9},
    },
    {
      id: 'dsh-workspace-plugin#workspace/memoryOpen',
      service: 'workspace',
      namespace: 'workspace',
      method: 'memoryOpen',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_memoryOpen_context$schema,
        },
      },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#MemoryScopeRequest',
            schema: dsh_workspace_plugin_workspace_memoryOpen_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#MemoryReadState',
        schema: dsh_workspace_plugin_workspace_memoryOpen_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":182,"column":9},
    },
    {
      id: 'dsh-workspace-plugin#workspace/memorySearch',
      service: 'workspace',
      namespace: 'workspace',
      method: 'memorySearch',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_memorySearch_context$schema,
        },
      },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#MemoryScopeRequest',
            schema: dsh_workspace_plugin_workspace_memorySearch_parameter_0$schema,
          },
        },
        {
          name: 'query',
          wire: 'query',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin#workspace/memorySearch:query',
            schema: dsh_workspace_plugin_workspace_memorySearch_parameter_1$schema,
          },
        },
        {
          name: 'options',
          wire: 'options',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#MemorySearchOptions',
            schema: dsh_workspace_plugin_workspace_memorySearch_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin#workspace/memorySearch:result',
        schema: dsh_workspace_plugin_workspace_memorySearch_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":207,"column":9},
    },
    {
      id: 'dsh-workspace-plugin#workspace/memoryUpsert',
      service: 'workspace',
      namespace: 'workspace',
      method: 'memoryUpsert',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_memoryUpsert_context$schema,
        },
      },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#MemoryScopeRequest',
            schema: dsh_workspace_plugin_workspace_memoryUpsert_parameter_0$schema,
          },
        },
        {
          name: 'draft',
          wire: 'draft',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#MemoryDraft',
            schema: dsh_workspace_plugin_workspace_memoryUpsert_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#MemoryRecord',
        schema: dsh_workspace_plugin_workspace_memoryUpsert_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":192,"column":9},
    },
    {
      id: 'dsh-workspace-plugin#workspace/previewArtifact',
      service: 'workspace',
      namespace: 'workspace',
      method: 'previewArtifact',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_previewArtifact_context$schema,
        },
      },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin#workspace/previewArtifact:id',
            schema: dsh_workspace_plugin_workspace_previewArtifact_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#WorkspaceArtifactPreview',
        schema: dsh_workspace_plugin_workspace_previewArtifact_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":176,"column":9},
    },
    {
      id: 'dsh-workspace-plugin#workspace/replaceContext',
      service: 'workspace',
      namespace: 'workspace',
      method: 'replaceContext',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_replaceContext_context$schema,
        },
      },
      parameters: [
        {
          name: 'snapshot',
          wire: 'snapshot',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#PinnedContextRemoteSnapshot',
            schema: dsh_workspace_plugin_workspace_replaceContext_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#PinnedContextRemoteSnapshot',
        schema: dsh_workspace_plugin_workspace_replaceContext_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":165,"column":3},
    },
    {
      id: 'dsh-workspace-plugin#workspace/summary',
      service: 'workspace',
      namespace: 'workspace',
      method: 'summary',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'agent',
          wire: 'agent',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#AgentId',
            schema: dsh_workspace_plugin_workspace_summary_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin#workspace/summary:result',
        schema: dsh_workspace_plugin_workspace_summary_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":150,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
