/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const WorkspaceJsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => WorkspaceJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => WorkspaceJsonValueRemoteCodec$schema)).readonly()])
const dsh_workspace_plugin_workspace_artifactMetadata_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_artifactMetadata_result$schema = z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'mediaType': z.string().readonly(),
  'sizeBytes': z.number().readonly(),
  'version': z.union([z.undefined(), z.string()]).readonly().optional(),
  'source': z.object({
  'sessionId': z.string().readonly(),
  'workspaceId': z.string().readonly(),
  'kind': z.union([z.literal("artifact"), z.literal("file")]).readonly(),
}).readonly(),
  'preview': z.union([z.literal("available"), z.literal("unsupported"), z.literal("oversized"), z.literal("stale")]).readonly(),
  'resourceId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'downloadName': z.string().readonly(),
  'altText': z.union([z.undefined(), z.string()]).readonly().optional(),
}))
const dsh_workspace_plugin_workspace_contextSnapshot_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_contextSnapshot_result$schema = z.object({
  'version': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'estimatedTokens': z.number().readonly(),
  'capacityTokens': z.number().readonly(),
  'admittedTokens': z.number().readonly(),
  'availableBudgetTokens': z.number().readonly(),
  'remainingTokens': z.number().readonly(),
  'status': z.union([z.literal("ready"), z.literal("omitted")]).readonly(),
  'omissionReason': z.string().readonly(),
})
const dsh_workspace_plugin_workspace_focus_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_focus_result$schema = z.object({
  'focused': z.boolean().readonly(),
})
const dsh_workspace_plugin_workspace_previewArtifact_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_previewArtifact_parameter_0$schema = z.string()
const dsh_workspace_plugin_workspace_previewArtifact_result$schema = z.union([z.object({
  'type': z.literal("text").readonly(),
  'renderer': z.literal("ui-primitives").readonly(),
  'language': z.union([z.undefined(), z.string()]).readonly().optional(),
  'content': z.string().readonly(),
  'truncated': z.boolean().readonly(),
}), z.object({
  'type': z.literal("markdown").readonly(),
  'renderer': z.literal("ui-primitives").readonly(),
  'content': z.string().readonly(),
  'truncated': z.boolean().readonly(),
  'policy': z.object({
  'allowRawHtml': z.literal(false).readonly(),
  'allowRemoteImages': z.literal(false).readonly(),
  'allowedLinkSchemes': z.tuple([z.literal("http"), z.literal("https"), z.literal("mailto")]).readonly(),
}).readonly(),
}), z.object({
  'type': z.literal("json").readonly(),
  'renderer': z.literal("ui-primitives").readonly(),
  'value': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.array(z.lazy(() => WorkspaceJsonValueRemoteCodec$schema)), z.record(z.string(), z.lazy(() => WorkspaceJsonValueRemoteCodec$schema)).readonly()]).readonly(),
}), z.object({
  'type': z.literal("csv").readonly(),
  'renderer': z.literal("ui-primitives").readonly(),
  'columns': z.array(z.string()).readonly(),
  'rows': z.array(z.array(z.string())).readonly(),
  'truncated': z.boolean().readonly(),
}), z.object({
  'type': z.literal("binary").readonly(),
  'mediaType': z.string().readonly(),
  'resourceId': z.string().readonly(),
  'version': z.string().readonly(),
  'expiresAt': z.number().readonly(),
}), z.object({
  'type': z.literal("unsupported").readonly(),
  'reason': z.string().readonly(),
  'mediaType': z.union([z.undefined(), z.string()]).readonly().optional(),
  'size': z.union([z.undefined(), z.number()]).readonly().optional(),
}), z.object({
  'type': z.literal("error").readonly(),
  'code': z.string().readonly(),
  'message': z.string().readonly(),
})])
const dsh_workspace_plugin_workspace_replaceContext_context$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_replaceContext_parameter_0$schema = z.object({
  'version': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'estimatedTokens': z.number().readonly(),
  'capacityTokens': z.number().readonly(),
  'admittedTokens': z.number().readonly(),
  'availableBudgetTokens': z.number().readonly(),
  'remainingTokens': z.number().readonly(),
  'status': z.union([z.literal("ready"), z.literal("omitted")]).readonly(),
  'omissionReason': z.string().readonly(),
})
const dsh_workspace_plugin_workspace_replaceContext_result$schema = z.object({
  'version': z.number().readonly(),
  'contentHash': z.string().readonly(),
  'estimatedTokens': z.number().readonly(),
  'capacityTokens': z.number().readonly(),
  'admittedTokens': z.number().readonly(),
  'availableBudgetTokens': z.number().readonly(),
  'remainingTokens': z.number().readonly(),
  'status': z.union([z.literal("ready"), z.literal("omitted")]).readonly(),
  'omissionReason': z.string().readonly(),
})
const dsh_workspace_plugin_workspace_summary_parameter_0$schema = z.intersection(z.string(), z.unknown())
const dsh_workspace_plugin_workspace_summary_result$schema = z.object({
  'ready': z.boolean().readonly(),
  'agent': z.intersection(z.string(), z.unknown()).readonly(),
})

export const TYPERT = {
  package: 'dsh-workspace-plugin',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-workspace-plugin#workspace/artifactMetadata',
      service: 'workspace',
      namespace: 'workspace',
      method: 'artifactMetadata',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_artifactMetadata_context$schema,
        },
      },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin#workspace/artifactMetadata:result',
        schema: dsh_workspace_plugin_workspace_artifactMetadata_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":132,"column":9},
    },
    {
      id: 'dsh-workspace-plugin#workspace/contextSnapshot',
      service: 'workspace',
      namespace: 'workspace',
      method: 'contextSnapshot',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_contextSnapshot_context$schema,
        },
      },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#PinnedContextRemoteSnapshot',
        schema: dsh_workspace_plugin_workspace_contextSnapshot_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":121,"column":3},
    },
    {
      id: 'dsh-workspace-plugin#workspace/focus',
      service: 'workspace',
      namespace: 'workspace',
      method: 'focus',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_focus_context$schema,
        },
      },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin#workspace/focus:result',
        schema: dsh_workspace_plugin_workspace_focus_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":116,"column":3},
    },
    {
      id: 'dsh-workspace-plugin#workspace/previewArtifact',
      service: 'workspace',
      namespace: 'workspace',
      method: 'previewArtifact',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_previewArtifact_context$schema,
        },
      },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin#workspace/previewArtifact:id',
            schema: dsh_workspace_plugin_workspace_previewArtifact_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#WorkspaceArtifactPreview',
        schema: dsh_workspace_plugin_workspace_previewArtifact_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":137,"column":9},
    },
    {
      id: 'dsh-workspace-plugin#workspace/replaceContext',
      service: 'workspace',
      namespace: 'workspace',
      method: 'replaceContext',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: 'dsh-workspace-plugin/types#AgentId',
          schema: dsh_workspace_plugin_workspace_replaceContext_context$schema,
        },
      },
      parameters: [
        {
          name: 'snapshot',
          wire: 'snapshot',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#PinnedContextRemoteSnapshot',
            schema: dsh_workspace_plugin_workspace_replaceContext_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin/types#PinnedContextRemoteSnapshot',
        schema: dsh_workspace_plugin_workspace_replaceContext_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":126,"column":3},
    },
    {
      id: 'dsh-workspace-plugin#workspace/summary',
      service: 'workspace',
      namespace: 'workspace',
      method: 'summary',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'agent',
          wire: 'agent',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-workspace-plugin/types#AgentId',
            schema: dsh_workspace_plugin_workspace_summary_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-workspace-plugin#workspace/summary:result',
        schema: dsh_workspace_plugin_workspace_summary_result$schema,
      },
      sourceLocation: {"file":"packages/plugin/src/index.ts","line":111,"column":3},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
